
services:
  mainserver:
    build:
      context: ./server
    container_name: mainserver
    ports:
      - "3009:3009"
    env_file:
      - ./server/.env
    environment:
      REDIS_HOST: my-redis
      REDIS_PORT: 6379
    networks:
      - vconnect_net
    restart: unless-stopped

  chatserver:
    build:
      context: ./chatServer
    container_name: chatserver
    ports:
      - "3011:3011"
    env_file:
      - ./chatServer/.env
    environment:                 
      REDIS_HOST: my-redis
      REDIS_PORT: 6379
    networks:
      - vconnect_net
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - vconnect_net
    restart: unless-stopped

networks:
  vconnect_net:
   # external: true 


